import { useEffect, useState } from 'react'

const emptyForm = { title: '', salaryMin: '', salaryMax: '', city: '', company: '', industry: '', headcount: 1, commission: 20, category: '', consultant: '', description: '' }

export default function JobFormModal({ job, onClose, onSave }) {
  const [form, setForm] = useState(emptyForm)
  useEffect(() => { setForm(job ? { title: job.title, salaryMin: job.salaryMin, salaryMax: job.salaryMax, city: job.city, company: job.company, industry: job.industry, headcount: job.headcount, commission: job.commission, category: job.category, consultant: job.consultant, description: job.description } : emptyForm) }, [job])
  if (job === undefined) return null
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }))
  const submit = event => { event.preventDefault(); if (!form.title.trim() || !form.company.trim()) return; onSave({ ...form, salaryMin: Number(form.salaryMin) || 0, salaryMax: Number(form.salaryMax) || 0, headcount: Number(form.headcount) || 1, commission: Number(form.commission) || 0 }) }
  return <div className="modal-backdrop" onClick={onClose}><form className="modal form-modal" onClick={event => event.stopPropagation()} onSubmit={submit}><div className="modal-header"><h2>{job ? '编辑职位' : '发布职位'}</h2><button type="button" onClick={onClose}>×</button></div><div className="form-grid"><label>职位名称<input name="title" value={form.title} onChange={update} required /></label><label>城市<input name="city" value={form.city} onChange={update} /></label><label>最低薪资<input name="salaryMin" type="number" min="0" value={form.salaryMin} onChange={update} /></label><label>最高薪资<input name="salaryMax" type="number" min="0" value={form.salaryMax} onChange={update} /></label><label>公司<input name="company" value={form.company} onChange={update} required /></label><label>行业<input name="industry" value={form.industry} onChange={update} /></label><label>招聘人数<input name="headcount" type="number" min="1" value={form.headcount} onChange={update} /></label><label>佣金比例<input name="commission" type="number" min="0" value={form.commission} onChange={update} /></label><label>职位类别<input name="category" value={form.category} onChange={update} /></label><label>顾问<input name="consultant" value={form.consultant} onChange={update} /></label><label className="form-full">职位描述<textarea name="description" value={form.description} onChange={update} rows="4" /></label></div><div className="form-actions"><button type="button" className="form-cancel" onClick={onClose}>取消</button><button type="submit" className="modal-primary">保存职位</button></div></form></div>
}
