import { useMemo, useState } from 'react'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import SearchSection from './components/SearchSection'
import JobToolbar from './components/JobToolbar'
import JobList from './components/JobList'
import JobDetailModal from './components/JobDetailModal'
import JobFormModal from './components/JobFormModal'
import JobManagementModal from './components/JobManagementModal'
import { loadJobs, saveJobs } from './utils/storage'
const initialFilters = { location: '不限', industry: '不限', zone: '不限', jobIndustry: '不限', category: '不限', status: '不限' }
const initialChecks = { '预充值剩余': false, '会员': false, '企业委托': false, '聚焦职位': false, '运作职位': true }
export default function App() { const [filters, setFilters] = useState(initialFilters); const [query, setQuery] = useState(''); const [checks, setChecks] = useState(initialChecks); const [jobs, setJobs] = useState(loadJobs); const [selectedJob, setSelectedJob] = useState(null); const [editingJob, setEditingJob] = useState(undefined); const [managementOpen, setManagementOpen] = useState(false); const filteredJobs = useMemo(() => jobs.filter(job => { const q = query.toLowerCase(); return (!q || job.title.toLowerCase().includes(q) || job.company.toLowerCase().includes(q)) && (filters.location === '不限' || job.city === filters.location) && (filters.category === '不限' || job.category === filters.category) }), [jobs, filters, query]); const clearFilters = () => { setFilters(initialFilters); setQuery('') }; const updateJobs = nextJobs => { setJobs(nextJobs); saveJobs(nextJobs) }; const randomStatus = () => ({ 加: Math.floor(Math.random() * 6), 推: Math.floor(Math.random() * 6), 初: Math.floor(Math.random() * 4), 复: Math.floor(Math.random() * 4), OF: Math.floor(Math.random() * 3), 职: Math.floor(Math.random() * 4) }); const saveJob = values => { const next = editingJob ? jobs.map(job => job.id === editingJob.id ? { ...job, ...values } : job) : [{ ...values, id: `job-${Date.now()}`, reviews: 0, aiRecommend: 0, status: randomStatus(), statusRandomized: true }, ...jobs]; updateJobs(next); setEditingJob(undefined) }; const deleteJob = job => { if (window.confirm('确定删除这个职位吗？')) updateJobs(jobs.filter(item => item.id !== job.id)) }; const editFromManagement = job => { setManagementOpen(false); setEditingJob(job) }; const deleteFromManagement = job => { deleteJob(job) }; return <div className="app-shell"><Header /><div className="page-layout"><Sidebar onPublish={() => setEditingJob(null)} onManage={() => setManagementOpen(true)} /><main className="main-content"><SearchSection filters={filters} onSelect={(key, value) => setFilters(current => ({ ...current, [key]: value }))} onClear={clearFilters} onSearch={setQuery} /><div className="result-count">为您查到 <strong>{query || filters.location !== '不限' || filters.category !== '不限' ? filteredJobs.length : 2509}</strong> 条结果</div><JobToolbar checked={checks} onToggle={label => setChecks(current => ({ ...current, [label]: !current[label] }))} /><JobList jobs={filteredJobs} onOpen={setSelectedJob} /></main></div><JobDetailModal job={selectedJob} onClose={() => setSelectedJob(null)} /><JobFormModal job={editingJob} onClose={() => setEditingJob(undefined)} onSave={saveJob} />{managementOpen && <JobManagementModal jobs={jobs} onClose={() => setManagementOpen(false)} onEdit={editFromManagement} onDelete={deleteFromManagement} />}</div> }
